# k8s/agents-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: budget-agent
  namespace: financial-advisor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: budget-agent
  template:
    metadata:
      labels:
        app: budget-agent
    spec:
      containers:
      - name: budget-agent
        image: gcr.io/PROJECT_ID/budget-agent:latest
        ports:
        - containerPort: 8080
        env:
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: gemini-secret
              key: api-key
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
