apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-server
  namespace: financial-advisor
  labels:
    app: mcp-server
    component: mcp-integration
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mcp-server
  template:
    metadata:
      labels:
        app: mcp-server
        component: mcp-integration
    spec:
      containers:
      - name: mcp-server
        image: REGION-docker.pkg.dev/PROJECT_ID/financial-advisor/mcp-server:latest
        ports:
        - containerPort: 8080
          name: http
        env:
        # Bank of Anthos service endpoints (individual microservices)
        - name: USERSERVICE_URL
          value: "http://userservice.default.svc.cluster.local:8080"
        - name: BALANCEREADER_URL
          value: "http://balancereader.default.svc.cluster.local:8080"
        - name: TRANSACTIONHISTORY_URL
          value: "http://transactionhistory.default.svc.cluster.local:8080"
        - name: CONTACTS_URL
          value: "http://contacts.default.svc.cluster.local:8080"
        # Optional: Frontend URL for reference
        - name: FRONTEND_URL
          value: "http://frontend.default.svc.cluster.local:80"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi" 
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        # Graceful shutdown
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 10"]
      # Restart policy
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: mcp-server
  namespace: financial-advisor
  labels:
    app: mcp-server
    component: mcp-integration
spec:
  selector:
    app: mcp-server
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  type: ClusterIP
  sessionAffinity: None
