# k8s/mcp-server-deployment.yaml - Corrected
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-server
  namespace: financial-advisor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mcp-server
  template:
    metadata:
      labels:
        app: mcp-server
    spec:
      containers:
      - name: mcp-server
        image: REGION-docker.pkg.dev/PROJECT_ID/financial-advisor/mcp-server:latest
        ports:
        - containerPort: 8080
        env:
        - name: BANK_ANTHOS_URL
          value: "http://frontend.default.svc.cluster.local:80"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi" 
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
