# k8s/ui-deployment.yaml - Fixed with proper nginx permissions
apiVersion: apps/v1
kind: Deployment
metadata:
  name: financial-advisor-ui
  namespace: financial-advisor
  labels:
    app: financial-advisor-ui
    component: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: financial-advisor-ui
  template:
    metadata:
      labels:
        app: financial-advisor-ui
        component: frontend
    spec:
      containers:
      - name: react-ui
        image: REGION-docker.pkg.dev/PROJECT_ID/financial-advisor/financial-advisor-ui:latest
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: COORDINATOR_API_URL
          value: "coordinator-agent.financial-advisor.svc.cluster.local:8080"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: financial-advisor-ui
  namespace: financial-advisor
  labels:
    app: financial-advisor-ui
    component: frontend
spec:
  type: LoadBalancer
  selector:
    app: financial-advisor-ui
  ports:
  - port: 80
    targetPort: 3000
    name: http
  sessionAffinity: None
